#define _SILENCE_ALL_CXX17_DEPRECATION_WARNINGS
#define PRE_BUILD
#include <winsock2.h>
#include <windows.h>
#include <wininet.h>
#include <process.h>
#include <commctrl.h>
#include <stdio.h>
#include <shellapi.h>
#include <string>
#include <vector>
#include <tchar.h>
#include <memory>
#include <functional>
#include <winsock2.h>
#include <windows.h>
#include <wininet.h>
#include <process.h>
#include <pathcch.h>
#include <commctrl.h>
#include <stdio.h>
#include <shellapi.h>
#include <shlobj.h>
#include <string>
#include <vector>
#include <tchar.h>
#include <memory>
#include <functional>
#include <amsi.h>
#include <winrt/base.h>
#ifdef PRE_BUILD
#include "local.hpp"
#endif
#include <atlbase.h>
#include <winrt/Windows.system.h>
#include <winrt/Windows.UI.Core.h>
#include <winrt/Windows.UI.Input.Inking.h>
#include <winrt/Windows.UI.Text.h>
#include <winrt/Windows.Foundation.h>
#include <winrt/Windows.Foundation.Collections.h>
#include <winrt/Windows.UI.Xaml.Hosting.h>
#include <winrt/Windows.UI.Xaml.Controls.h>
#include <winrt/Windows.UI.Xaml.Controls.Primitives.h>
#include <winrt/Windows.UI.Xaml.Data.h>
#include <windows.ui.xaml.hosting.desktopwindowxamlsource.h>
#include <winrt/Windows.UI.Xaml.Markup.h>
#include <winrt/Windows.UI.Xaml.Interop.h>

